import { JsonController, Get, Res } from 'routing-controllers';
import { Response } from 'express';
import { Injectable } from '@shared/utils/ioc.util';
import { OpenApiService } from '@domains/openapi/openapi.service';

/**
 * Controller to serve the OpenAPI JSON specification.
 */
@JsonController('/api')
@Injectable()
export class OpenapiController {
  constructor(private readonly openApiService: OpenApiService) {}

  /**
   * Return the OpenAPI spec generated by OpenApiService
   */
  @Get('/openapi.json')
  getSpec(@Res() res: Response): Response {
    const spec = this.openApiService.generateSpec();
    return res.json(spec);
  }
}
